"""empty message

Revision ID: 805c571fa670
Revises: 8e6241d5639b
Create Date: 2019-02-19 21:17:40.840550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805c571fa670'
down_revision = '8e6241d5639b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userid')
    # ### end Alembic commands ###
