from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, validators
import os
import numpy as np
import csv
from flask import current_app
import app



#v = np.genfromtxt("v.csv", delimiter=',') # This is the transpose of v or v.T as generated by scipy.sparse.linalg.svds
#s = np.genfromtxt("s.csv", delimiter=',')
#users = pd.read_csv("users.csv")
class WordToWord(FlaskForm):
    wordOne = StringField('First Word', id='term', default="trump")
    wordTwo = StringField('Second Word', id='term2', default="liberal")
    submit = SubmitField('Compare')

class WordToAll(FlaskForm):
    term = StringField('Search Term', id="term", default="trump")
    numWords = IntegerField("Number of Terms", default=10, validators=[validators.NumberRange(1,30,
                                            message="Please Choose a number less than 30")])
    submit = SubmitField('Find Similar')

class WordToUser(FlaskForm):
    term = StringField('Search Term', id="term", default="republican")
    user = StringField('User Name', id="userOne", default="TEN_GOP")
    submit = SubmitField("Compare")

class UserToUser(FlaskForm):
    userOne = StringField("First User", id="userOne", default="TEN_GOP")
    userTwo = StringField("Second User", id="userTwo", default="blackmattersus")
    submit = SubmitField("Compare")

class UserToAll(FlaskForm):
    user = StringField('User', id="userOne", default="NewOrleansON")
    numUsers = IntegerField("Number of Users", default=10, validators=[validators.NumberRange(1,30,
                                              message="Please Choose a number less than 30")])
    submit = SubmitField("Find Similar")

class WordToAllUsers(FlaskForm):
    term = StringField("Term", id="term", default="republican")
    numUsers = IntegerField("Number of Users", default=10, validators=[validators.NumberRange(1,30,
                                              message="Please Choose a number less than 30")])
    submit = SubmitField("Find Similar Users")

class UserNetwork(FlaskForm):
    user = StringField('User', id="userOne", default="TEN_GOP")
    numUsers = IntegerField("Number of Users", default = 15, validators=[validators.NumberRange(1,30,
                                            message="Please Choose a number less than 30")])
    submit = SubmitField("Build Network")
