from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, validators
import os
import numpy as np
import csv
from flask import current_app
import app



#v = np.genfromtxt("v.csv", delimiter=',') # This is the transpose of v or v.T as generated by scipy.sparse.linalg.svds
#s = np.genfromtxt("s.csv", delimiter=',')
#users = pd.read_csv("users.csv")
class WordToWord(FlaskForm):
    wordOne = StringField('First Word', id='term')
    wordTwo = StringField('Second Word', id='term2')
    submit = SubmitField('Compare')

class WordToAll(FlaskForm):
    term = StringField('Search Term', id="term")
    numWords = IntegerField("Number of Terms", validators=[validators.NumberRange(1,30,
                                            message="Please Choose a number less than 30")])
    submit = SubmitField('Find Similar')

class WordToUser(FlaskForm):
    term = StringField('Search Term', id="term")
    user = StringField('User Name', id="userOne")
    submit = SubmitField("Compare")

class UserToUser(FlaskForm):
    userOne = StringField("First User", id="userOne")
    userTwo = StringField("Second User", id="userTwo")
    submit = SubmitField("Compare")

class UserToAll(FlaskForm):
    user = StringField('User', id="userOne")
    numUsers = IntegerField("Number of Users", validators=[validators.NumberRange(1,30,
                                              message="Please Choose a number less than 30")])
    submit = SubmitField("Find Similar")

class WordToAllUsers(FlaskForm):
    term = StringField("Term", id="term")
    numUsers = IntegerField("Number of Users", validators=[validators.NumberRange(1,30,
                                              message="Please Choose a number less than 30")])
    submit = SubmitField("Find Similar Users")